algoritmo "media_tres_notas"
// autor: nicolas
// data: 13/04/26
var
   N1, N2, N3, Media: real
// começar o código da média
inicio
   escreva("Digite a primeira nota: ")
   leia(N1)
   escreva("Digite a segunda nota: ")
   leia(N2)
   escreva("Digite a terceira nota: ")
   leia(N3)
// resultado final da média

   Media <- (N1 + N2 + N3) / 3

   escreval("Média: ", Media)




